### ISSUE TITLE
Stuck Objects in TUIOClient

### ISSUE THREAD

**Issue by bildwerktv** [vvvv/VL.IO.TUIO#1]
Sometimes Objects get Stuck in the HoldLatest Node. 
Enabling/Disabling the Tuio Client should also reset the HoldLatest Nodes and/or add dedicated Reset Pin

**Comment by joreg** [comment]
good point regarding resetting the outputs on disable. i fixed that in 1.0.6.

but it would also be interesting to solve the initial problem of "Sometimes Objects get Stuck in the HoldLatest Node." is there a way to reproduce this? or did you mean this happened when you disable the TUIOClient?

**Comment by bildwerktv** [comment]
We found no way to reproduce it. But it happens. The best kind of bugs :D
It manifests in a way that there is one entry in the Cursors that stays constant, but in our application breaks the Touch Injection downstream and no new Touches will get injected if the one is stuck. So we made a simple workaround to reset the Touchpoints.

**Comment by joreg** [comment]
ok, so then we'll re-open this issue once there is a way to reproduce the problem.
